//
// Shape.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Shape: Codable, JSONEncodable, Hashable {
    case typeCircle(Circle)
    case typeSquare(Square)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCircle(let value):
            try container.encode(value)
        case .typeSquare(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case kind = "kind"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .kind)

        switch discriminatorValue {
        case "circle":
            self = .typeCircle(try Circle(from: decoder))
        case "square":
            self = .typeSquare(try Square(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for Shape"
                )
            )
        }
    }

    public var id: String? {
        switch self {
        case .typeCircle(let value): return value.id
        case .typeSquare(let value): return value.id
        }
    }

    public var label: String? {
        switch self {
        case .typeCircle(let value): return value.label
        case .typeSquare(let value): return value.label
        }
    }

    public var kind: String? {
        switch self {
        case .typeCircle(let value): return value.kind
        case .typeSquare(let value): return value.kind
        }
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Shape: Identifiable {}
