//
// Circle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Circle: Sendable, Codable, Hashable {

    public var id: String?
    public var label: String?
    public var kind: String?
    public var onlyOnCircle: String?
    public var radius: Double?

    public init(id: String? = nil, label: String? = nil, kind: String? = nil, onlyOnCircle: String? = nil, radius: Double? = nil) {
        self.id = id
        self.label = label
        self.kind = kind
        self.onlyOnCircle = onlyOnCircle
        self.radius = radius
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case kind
        case onlyOnCircle
        case radius
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(onlyOnCircle, forKey: .onlyOnCircle)
        try container.encodeIfPresent(radius, forKey: .radius)
    }
}


extension Circle: Identifiable {}
