//
// Square.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Square: Sendable, Codable, Hashable {

    public var id: String?
    public var label: String?
    public var kind: String?
    public var side: Double?

    public init(id: String? = nil, label: String? = nil, kind: String? = nil, side: Double? = nil) {
        self.id = id
        self.label = label
        self.kind = kind
        self.side = side
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case kind
        case side
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(side, forKey: .side)
    }
}


extension Square: Identifiable {}
