/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * 
 *
 */
@Serializable(with = AnyOfBooleanOrDoubleOrStringSerializer::class)

sealed interface AnyOfBooleanOrDoubleOrString {
    @JvmInline
    value class BooleanValue(val value: kotlin.Boolean) : AnyOfBooleanOrDoubleOrString

    @JvmInline
    value class DoubleValue(val value: kotlin.Double) : AnyOfBooleanOrDoubleOrString

    @JvmInline
    value class StringValue(val value: kotlin.String) : AnyOfBooleanOrDoubleOrString

}

object AnyOfBooleanOrDoubleOrStringSerializer : KSerializer<AnyOfBooleanOrDoubleOrString> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("AnyOfBooleanOrDoubleOrString")

    override fun serialize(encoder: Encoder, value: AnyOfBooleanOrDoubleOrString) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("AnyOfBooleanOrDoubleOrString can only be serialized with Json")

        when (value) {
            is AnyOfBooleanOrDoubleOrString.BooleanValue -> jsonEncoder.encodeBoolean(value.value)
            is AnyOfBooleanOrDoubleOrString.DoubleValue -> jsonEncoder.encodeDouble(value.value)
            is AnyOfBooleanOrDoubleOrString.StringValue -> jsonEncoder.encodeString(value.value)
        }
    }

    override fun deserialize(decoder: Decoder): AnyOfBooleanOrDoubleOrString {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("AnyOfBooleanOrDoubleOrString can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Boolean>(jsonElement)
                return AnyOfBooleanOrDoubleOrString.BooleanValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Boolean: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Double>(jsonElement)
                return AnyOfBooleanOrDoubleOrString.DoubleValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Double: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.String>(jsonElement)
                return AnyOfBooleanOrDoubleOrString.StringValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.String: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize AnyOfBooleanOrDoubleOrString. Tried: ${errorMessages.joinToString(", ")}")
    }
}

