/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * 
 *
 */
@Serializable(with = BooleanOrDoubleOrStringSerializer::class)
internal sealed interface BooleanOrDoubleOrString {
    @JvmInline
    value class BooleanValue(internal val value: kotlin.Boolean) : BooleanOrDoubleOrString

    @JvmInline
    value class DoubleValue(internal val value: kotlin.Double) : BooleanOrDoubleOrString

    @JvmInline
    value class StringValue(internal val value: kotlin.String) : BooleanOrDoubleOrString

}

internal object BooleanOrDoubleOrStringSerializer : KSerializer<BooleanOrDoubleOrString> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("BooleanOrDoubleOrString")

    override fun serialize(encoder: Encoder, value: BooleanOrDoubleOrString) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("BooleanOrDoubleOrString can only be serialized with Json")

        when (value) {
            is BooleanOrDoubleOrString.BooleanValue -> jsonEncoder.encodeBoolean(value.value)
            is BooleanOrDoubleOrString.DoubleValue -> jsonEncoder.encodeDouble(value.value)
            is BooleanOrDoubleOrString.StringValue -> jsonEncoder.encodeString(value.value)
        }
    }

    override fun deserialize(decoder: Decoder): BooleanOrDoubleOrString {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("BooleanOrDoubleOrString can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Boolean>(jsonElement)
                return BooleanOrDoubleOrString.BooleanValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Boolean: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Double>(jsonElement)
                return BooleanOrDoubleOrString.DoubleValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Double: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.String>(jsonElement)
                return BooleanOrDoubleOrString.StringValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.String: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize BooleanOrDoubleOrString. Tried: ${errorMessages.joinToString(", ")}")
    }
}

