/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * 
 *
 */
@Serializable(with = FloatOrIntSerializer::class)
internal sealed interface FloatOrInt {
    @JvmInline
    value class FloatValue(internal val value: kotlin.Float) : FloatOrInt

    @JvmInline
    value class IntValue(internal val value: kotlin.Int) : FloatOrInt

}

internal object FloatOrIntSerializer : KSerializer<FloatOrInt> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("FloatOrInt")

    override fun serialize(encoder: Encoder, value: FloatOrInt) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("FloatOrInt can only be serialized with Json")

        when (value) {
            is FloatOrInt.FloatValue -> jsonEncoder.encodeFloat(value.value)
            is FloatOrInt.IntValue -> jsonEncoder.encodeInt(value.value)
        }
    }

    override fun deserialize(decoder: Decoder): FloatOrInt {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("FloatOrInt can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Float>(jsonElement)
                return FloatOrInt.FloatValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Float: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && !jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.Int>(jsonElement)
                return FloatOrInt.IntValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.Int: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize FloatOrInt. Tried: ${errorMessages.joinToString(", ")}")
    }
}

